driver:
  name: dokken
  privileged: true
  # our cookbooks should be compatible with the latest Chef,
  # but we nee to ensure they still work on 13 until we move to 14
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

platforms:
  - name: ubuntu-20.04
    driver:
      image: dokken/ubuntu-20.04
      pid_one_command: /bin/systemd
  - name: ubuntu-22.04
    driver:
      image: dokken/ubuntu-22.04
      pid_one_command: /bin/systemd

provisioner:
  name: dokken
  chef_log_level: <%= ENV['CHEF_LOG_LEVEL'] || 'auto' %>

transport:
  name: dokken

suites:
  - name: default
    run_list:
      - recipe[ci_fixes]
      - recipe[fb_init_sample]
